version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_sge
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - sge_net

  postgres:
    image: postgres:15
    container_name: postgres_sge
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sge_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sge_net

networks:
  sge_net:

volumes:
  postgres_data:

